### ISSUE TITLE
Grafana setup

### ISSUE THREAD

**Issue by UCCNetworkingSociety** [UCCNetsoc/NaC#11]
We need to setup Grafana on the new system to pull from the Prometheus server

We should consider using this to define dashboards
https://github.com/grafana/grafonnet-lib

**Comment by UCCNetworkingSociety** [comment]
There was a lovely talk about Grafana-As-Code at FOSDEM that I missed while being stuck in bed severely hungover, recommended watch

https://fosdem.org/2020/schedule/event/grafana_as_code/

**Comment by Strum355** [comment]
Great talk, worth a watch ^

**Comment by ocanty** [comment]
in progress - need to do the recommit solution, grafonnet is a pain in the ass to manage so just c+ping the dashboard json into a folder is genuinely easier

**Comment by ericm** [comment]
Resolved by exporter https://github.com/UCCNetsoc/NaC/blob/master/export-grafana-dashboards.yml
