### ISSUE TITLE
Prometheus exporter & Prometheus server setup

### ISSUE THREAD

**Issue by UCCNetworkingSociety** [UCCNetsoc/NaC#6]
We need to get monitoring working on the new Proxmox setup, so someone needs to write a playbook that sets up Prometheus exporters on every server.

For now, they can create a new test vm with a new `create-*.yml` playbook. They will then need to target this vm with a similar `provision-.yml` playbook. This should install the following Prometheus exporters (preferably) in Docker:

* cadvisor
* node_exporter
* ipmi_exporter (maybe?)

These exporters should be reverse proxified by expexp_exporter

There is an existing implementation of this in `roles/prometheus-exporters` but I do not know how well it works/if at all. I think I moved it originally from a playbook to a role

Whoever completes this issue will also need to setup a Prometheus server (probably on the docker swarm in `provision-docker-swarm-services.yml`) that collects the metrics exported by the testvm

Once we have the test vm working, we can call the playbook on all our vms and setup metrics for everything

**Comment by ocanty** [comment]
https://wiki.netsoc.co/en/sysadmin/alerts-&-monitoring document as-well
