### ISSUE TITLE
Offsite-backup

### ISSUE THREAD

**Issue by UCCNetworkingSociety** [UCCNetsoc/NaC#8]
Currently it's possible to configure Proxmox to perform a backup jobs on certain days of the week. This converts the VM into a "vzdump" basically a compressed archive of it's settings and disks. A Proxmox backup job will create vzdumps for all of the VMs in the cluster

We want to create a job that will backup these backups to something like Google Drive. 
It's important that we compress these backups again as many of the boot disks on the VMs are very similar. The vzdumps are per VM rather than per cluster so there's a lot of duplicated data

We could potentially ignore Proxmoxes backup job system altogether and write our own system that calls vzdump manually to ignore the boot drive and just backup the 2nd disk (which we explicitly use to store volatile data)

The system we could use to backup stuff to GDrive will probably be Duplicati

**Comment by ericm** [comment]
- Using cronjob. VZDump conditions: *.vm.netsoc.co, 2 disks, 2nd disk only.
- `pvesh` to interface with api.
- Monitoring by likely calling a webhook for discord notifications within the crontab

**Comment by ocanty** [comment]
Also `qm` if you just care about what's on the current host

**Comment by ocanty** [comment]
Also have a look at: https://github.com/UCCNetsoc/NaC/blob/master/roles/packer-proxmox-template/tasks/main.yml#L199

This is how we rsync a vzdump of the template machine from the template build host to all the other hosts
See `docs/infra.md` for a more thorough explanation

**Comment by ocanty** [comment]
Just to document I got confused, we're meant to be using _duplicity_ not _duplicati_
http://duplicity.nongnu.org/

**Comment by ocanty** [comment]
we could maybe explore https://forum.proxmox.com/threads/proxmox-backup-server-beta.72676/

would probably run it as it's own vm, unless anyone can think of a reason not to

**Comment by ericm** [comment]
I'll look into it. Still use duplicity for remote backup?

**Comment by ericm** [comment]
So the server uses DataStores which can be used to store the backup archives. The client can be used to backup snapshots of VMs or paths on the host. I can't find anything on scheduling the client on the hosts so we may have to stick with cron for that.

**Comment by ericm** [comment]
Also the DataStores have pruning and garbage collection :)

**Comment by ericm** [comment]
We also need to decided whether we want each host to be a client or each VM. I'd say running the client periodically on each VM would be more ideal but may require more work / deployment.

**Comment by ericm** [comment]
done
