### ISSUE TITLE
Move existing services over

### ISSUE THREAD

**Issue by UCCNetworkingSociety** [UCCNetsoc/NaC#9]
Most of the services are still running on the legacy system

We need to move these over:
- CI
- Grafana
- ES/Kibana
- etc
- (maybe more, pls list in replies)

These will need to be moved to the Proxmox system

**Comment by ocanty** [comment]
@Thomas007G think you could do CI?

**Comment by ocanty** [comment]
discord.netsoc.co, esports.netsoc.co, blog and website have been moved, just need to update DNS records
